--- #YAML:1.0
name:               Bio-LITE-Taxonomy-NCBI-Gi2taxid
version:            0.03
abstract:           Mappings of NCBI GIs to Taxids fast and with very low memory footprint.
author:
    - Miguel Pignatelli <emepyc@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    File::Tail:  0.96
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
