---
abstract: 'Mappings of NCBI GIs to Taxids fast and with very low memory footprint.'
author:
  - 'Miguel Pignatelli <emepyc@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Bio-LITE-Taxonomy-NCBI-Gi2taxid
no_index:
  directory:
    - t
    - inc
requires:
  File::Tail: 0.96
  Test::More: 0
version: 0.05
